version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache2
    build: 
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - db2
    image: php:8.2-apache
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8080:80
  db2:
    container_name: db2
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql1122
      MYSQL_DATABASE: my_database
      MYSQL_USER: justthisuser
      MYSQL_PASSWORD: mysqlpass1122
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8000:80"
    restart: always
    environment:
      PMA_HOST: db2
    depends_on:
      - db2